name: AVANTI MIX ROOM 1
favicon: null
layout_spectrum: 0.02221680828370154
typography_spectrum: 0.6042493432760239
title: AVANTI Mix Room 1st edit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#646464'
    - '#f60053'
    - '#c2c2c2'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
